StoreLocator.Web/Models/UserViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace StoreLocator.Web.Models
{
    public class UserViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Enter Your UserName")]
        [StringLength(4, ErrorMessage = "User Name should be min four characters and max 20 characters.")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Enter Your Password")]
        [StringLength(4, ErrorMessage = "Password should be min four characters and max 20 characters.")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Enter Your Email")]
        [RegularExpression(@"^[\w-\._\+%]+@(?:[\w-]+\.)+[\w]{2,6}$", ErrorMessage = "Please enter a valid email address")]
        public string Email { get; set; }

        public bool Admin { get; set; }

        public bool Active { get; set; }
    }
}

StoreLocator.Web/Controllers/PurchaseController.cs
using StoreLocator.Models;
using StoreLocator.Provider;
using StoreLocator.Web.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace StoreLocator.Web.Controllers
{
    [Authorize]
    public class PurchaseController : Controller
    {
        public ActionResult Index()
        {
            if (Session["UserId"] != null)
            {
                var purchaseList = new PurchaseProvider().GetPurchases(int.Parse(Session["UserId"].ToString()));

                if (purchaseList != null && purchaseList.Count > 0)
                {
                    var purchaseViewModelList = new List<PurchaseViewModel>();

                    foreach (var purchaseItem in purchaseList)
                    {
                        var purchaseViewModel = new PurchaseViewModel
                        {
                            Id = purchaseItem.Id,
                            UserId = purchaseItem.UserId,
                            Date = purchaseItem.Date,
                            Description = purchaseItem.Description,
                            VatApplied = purchaseItem.VatApplied,
                            Active = purchaseItem.Active,
                            NetAmount = purchaseItem.NetAmount
                        };

                        purchaseViewModelList.Add(purchaseViewModel);
                    }

                    return View(purchaseViewModelList.AsEnumerable());
                }
            }

            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(PurchaseViewModel purchaseViewModel)
        {
            if (purchaseViewModel != null)
            {                       
                var createPurchaseModel = new Purchase()
                {
                    UserId = int.Parse(Session["UserId"].ToString()),
                    Date = purchaseViewModel.Date,
                    Description = purchaseViewModel.Description,
                    NetAmount = purchaseViewModel.NetAmount,
                    VatApplied = purchaseViewModel.VatApplied,
                    Active = true
                };

                var purchaseId = new PurchaseProvider().CreatePurchase(createPurchaseModel);
                if (!string.IsNullOrEmpty(purchaseId))
                {
                    return RedirectToAction("Index");
                }                                    
            }

            return View();
        }
    }
}

StoreLocator.Web/Controllers/SaleController.cs
using StoreLocator.Models;
using StoreLocator.Provider;
using StoreLocator.Web.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace StoreLocator.Web.Controllers
{
    [Authorize]
    public class SaleController : Controller
    {
        public ActionResult Index()
        {
            if (Session["UserId"] != null)
            {
                var saleList = new SaleProvider().GetSales(int.Parse(Session["UserId"].ToString()));

                if (saleList != null && saleList.Count > 0)
                {
                    var saleViewModelList = new List<SaleViewModel>();

                    foreach (var saleItem in saleList)
                    {
                        var saleViewModel = new SaleViewModel
                        {
                            Id = saleItem.Id,
                            UserId = saleItem.UserId,
                            Date = saleItem.Date,
                            Description = saleItem.Description,
                            VatApplied = saleItem.VatApplied,
                            Active = saleItem.Active,
                            NetAmount = saleItem.NetAmount
                        };

                        saleViewModelList.Add(saleViewModel);
                    }

                    return View(saleViewModelList.AsEnumerable());
                }
            }

            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(SaleViewModel saleViewModel)
        {
            if (saleViewModel != null)
            {                       
                var createSaleModel = new Sale()
                {
                    UserId = int.Parse(Session["UserId"].ToString()),
                    Date = saleViewModel.Date,
                    Description = saleViewModel.Description,
                    NetAmount = saleViewModel.NetAmount,
                    VatApplied = saleViewModel.VatApplied,
                    Active = true
                };

                var saleId = new SaleProvider().CreateSale(createSaleModel);
                if (!string.IsNullOrEmpty(saleId))
                {
                    return RedirectToAction("Index");
                }                                    
            }

            return View();
        }
    }
}

StoreLocator.Web/Controllers/UserController.cs
using StoreLocator.Models;
using StoreLocator.Provider;
using StoreLocator.Web.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace StoreLocator.Web.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        public ActionResult Index()
        {
            if (Session["IsAdmin"] == null)
            {
                return View("~/Views/Home.cshtml");
            }

            var userList = new UserProvider().GetUsers();

            if (userList != null && userList.Count > 0)
            {
                var userViewModelList = new List<UserViewModel>();

                foreach (var userItem in userList)
                {
                    var userViewModel = new UserViewModel();
                    userViewModel.Id = userItem.Id;
                    userViewModel.UserName = userItem.Name;
                    userViewModel.Password = userItem.Password;
                    userViewModel.Email = userItem.Email;
                    userViewModel.Admin = userItem.Admin;
                    userViewModel.Active = userItem.Active;
                    userViewModelList.Add(userViewModel);
                }

                return View(userViewModelList.AsEnumerable());
            }

            return View();
        }

        public ActionResult Create()
        {
            if (Session["IsAdmin"] == null)
            {
                return View("~/Views/Home.cshtml");
            }

            return View();
        }

        [HttpPost]
        public ActionResult Create(UserViewModel userViewModel)
        {
            if (Session["IsAdmin"] == null)
            {
                return View("~/Views/Home.cshtml");
            }

            if (userViewModel != null)
            {
                var userList = new UserProvider().GetUsers();

                if (userList != null && userList.Count > 0)
                {
                    if (!userList.Any(item => item.Name.Equals(userViewModel.UserName)))
                    {
                        var createUserModel = new User()
                        {
                            Name = userViewModel.UserName,
                            Password = userViewModel.Password,
                            Email = userViewModel.Email,
                            Admin = userViewModel.Admin,
                            Active = userViewModel.Active
                        };

                        var userId = new UserProvider().CreateUser(createUserModel);
                        if (!string.IsNullOrEmpty(userId))
                        {
                            return RedirectToAction("Index");
                        }
                    }
                }
            }

            return View();
        }

        public ActionResult Edit(int id)
        {
            if (Session["IsAdmin"] == null)
            {
                return View("~/Views/Home.cshtml");
            }

            if (id <= 0)
            {
                return RedirectToAction("Index");
            }

            var userList = new UserProvider().GetUsers();
            var user = userList.SingleOrDefault(item => item.Id == id);
            if (user != null)
            {
                var editUserViewModel = new UserViewModel()
                {
                    Id = user.Id,
                    UserName = user.Name,
                    Password = user.Password,
                    Email = user.Email,
                    Admin = user.Admin,
                    Active = user.Active
                };

                return View(editUserViewModel);
            }

            return View();
        }

        [HttpPost]
        public ActionResult Edit(UserViewModel editUserViewModel)
        {
            if (Session["IsAdmin"] == null)
            {
                return View("~/Views/Home.cshtml");
            }

            if (editUserViewModel != null)
            {
                var updateUserModel = new User()
                {
                    Id = editUserViewModel.Id,
                    Name = editUserViewModel.UserName,
                    Password = editUserViewModel.Password,
                    Email = editUserViewModel.Email,
                    Admin = editUserViewModel.Admin,
                    Active = editUserViewModel.Active
                };

                var user = new UserProvider().UpdateUser(updateUserModel);
                return RedirectToAction("Index");
            }
            
            return View();
        }
    }
}

StoreLocator.Web/Views/User/Create.cshtml
@model StoreLocator.Web.Models.UserViewModel

<br />
<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 header-text text-center">
                <h5 class="mb-10">
                    @if (Session["IsAdmin"] != null)
                    {
                        @Html.ActionLink("Users", "Index", "User");
                        <span>||</span>
                    }

                    @Html.ActionLink("Sales", "Index", "Sale") ||
                    @Html.ActionLink("Purchases", "Index", "Purchase")
                </h5>
            </div>
        </div>
    </div>
</section>

<br />
<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 header-text text-center">
                <h1 class="mb-10">Welcome @User.Identity.Name</h1>
            </div>
            <div class="col-md-12 header-text text-center">
                <h5 class="mb-10">Create a new user</h5>
            </div>
        </div>
    </div>
</section>
<!-- End Sample Area -->
<br />
<br />

<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 header-text">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Admin, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.Admin)
                                    @Html.ValidationMessageFor(model => model.Admin, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.Active)
                                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group text-center">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>
<!-- End Sample Area -->
<br />
<br />

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoreLocator.Web/Views/User/Edit.cshtml
@model StoreLocator.Web.Models.UserViewModel

<br />
<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 header-text text-center">
                <h5 class="mb-10">
                    @if (Session["IsAdmin"] != null)
                    {
                        @Html.ActionLink("Users", "Index", "User");
                        <span>||</span>
                    }

                    @Html.ActionLink("Sales", "Index", "Sale") ||
                    @Html.ActionLink("Purchases", "Index", "Purchase")
                </h5>
            </div>
        </div>
    </div>
</section>

<br />
<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 header-text text-center">
                <h1 class="mb-10">Welcome @User.Identity.Name</h1>
            </div>
            <div class="col-md-12 header-text text-center">
                <h5 class="mb-10">Edit user</h5>
            </div>
        </div>
    </div>
</section>
<!-- End Sample Area -->
<br />
<br />

<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 header-text">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">                        
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Admin, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.Admin)
                                    @Html.ValidationMessageFor(model => model.Admin, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.Active)
                                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group text-center">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>
<!-- End Sample Area -->
<br />
<br />

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoreLocator.Web/Views/User/Index.cshtml
@model IEnumerable<StoreLocator.Web.Models.UserViewModel>

<br />
<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 header-text text-center">
                <h5 class="mb-10">
                    @if (Session["IsAdmin"] != null)
                    {
                        @Html.ActionLink("Users", "Index", "User");
                        <span>||</span>
                    }

                    @Html.ActionLink("Sales", "Index", "Sale") ||
                    @Html.ActionLink("Purchases", "Index", "Purchase")
                </h5>
            </div>
        </div>
    </div>
</section>

<br />
<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 header-text text-center">
                <h1 class="mb-10">Welcome @User.Identity.Name</h1>
            </div>
        </div>
    </div>
</section>
<!-- End Sample Area -->
<br />
<br />

<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 header-text text-center">
                <p>
                    @Html.ActionLink("Create New", "Create")
                </p>
                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.UserName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Password)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Email)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Admin)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Active)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.UserName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Password)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Admin)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Active)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                            </td>
                        </tr>
                    }

                </table>
            </div>
        </div>
    </div>
</section>
<!-- End Sample Area -->
<br />
<br />